In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [43]:
lr=LogisticRegression(max_iter=400)
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)


0.9740740740740741

In [44]:
svm=SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9944444444444445

In [45]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9722222222222222

In [53]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [54]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [48]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [49]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [55]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,Y_train,Y_test= digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(lr,X_train,X_test,Y_train,Y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
    scores_rf.append(get_score(rf,X_train,X_test,Y_train,Y_test))

In [56]:
scores_l

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [57]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [58]:
scores_rf

[0.9198664440734557, 0.9465776293823038, 0.9248747913188647]